apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: OpenIdClient
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/openidclient
  labels:
    testing.upbound.io/example-name: openid_client
  name: openid-client
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientId: test-client
    enabled: true
    extraConfig:
      key1: value1
      key2: value2
    loginTheme: keycloak
    name: test client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    validRedirectUris:
    - http://localhost:8080/openid-callback

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/openidclient
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: example
