apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: SamlClient
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/samlclient
  labels:
    testing.upbound.io/example-name: saml_client
  name: saml-client
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    includeAuthnStatement: true
    name: saml-client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    signAssertions: true
    signDocuments: false
    signingCertificate: ${file("saml-cert.pem")}
    signingPrivateKey: ${file("saml-key.pem")}

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/samlclient
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
