---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: dev-default-group
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: dev
    name: dev-default-group
  initProvider: {}
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: dev-default-group-roles
spec:
  deletionPolicy: Delete
  forProvider:
    groupIdRef:
      name: dev-default-group
    realmId: dev
    #roleIds:
    #  - a1016794-5600-48ce-85d8-1a01274b3767
    roleIdsRefs:
      - name: builtin-dev-realm-role-uma-authorization
    #roleIdsSelector:
    #  matchLabels:
    #    defaultRole: 'true'
    #    realmName: my-realm
  managementPolicies:
    - '*'
  providerConfigRef:
    name: "keycloak-provider-config"